import { createFileRoute } from '@tanstack/react-router';
import Landing from '../components/Landing';
import Header from '../components/Header';
import Footer from '../components/Footer';

export const Route = createFileRoute('/')({
  head: () => ({
    meta: [
      {
        title: 'auri - Language Immersion Through Dictation',
      },
      {
        name: 'description',
        content: 'Improve your listening and speaking skills with personalized, daily lessons generated by AI.',
      },
      {
        property: 'og:title',
        content: 'auri - Language Immersion Through Dictation',
      },
      {
        property: 'og:description',
        content: 'Improve your listening and speaking skills with personalized, daily lessons generated by AI.',
      },
    ],
  }),
  component: App,
})


function App() {
  return (
    <main className="max-w-6xl mx-auto min-h-screen px-6 py-12 md:py-24 flex flex-col">
      <Header />

      <div className="flex-grow">
        <Landing />
      </div>

      <Footer />
    </main>
  );
}
